### ISSUE TITLE
Compliation error  

### ISSUE THREAD

**Issue by dcabanis** [luojia65/trustzone-m-rs#1]
Hello, I have just seen your post on twitter. I have an existing Rust embedded development environment on Ubuntu 20.04.
Running the cargo qemu command, I get the error message:

   Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/xtask qemu`
xtask: make application and run in QEMU
   Compiling secure-app v0.1.0 (/home/dcabanis/Documents/rust/TrustZone_QEMU/trustzone-m-rs/secure-app)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> secure-app/src/main.rs:1:1
  |
1 | #![feature(abi_c_cmse_nonsecure_call, cmse_nonsecure_entry)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `secure-app` due to previous error
xtask: cargo build failed with exit status: 101

Do you have any ideas about what I am missing?

**Comment by dcabanis** [comment]
I have enabled nightly instead of stable and I think I am getting better results:

Invalid access at addr 0x10000000, size 4, region '(null)', reason: rejected
Invalid access at addr 0x10000004, size 4, region '(null)', reason: rejected
Hello from Secure World!
BLXNS with misaligned SP is UNPREDICTABLE
Hello from Non-Secure World!
secure function called!
secure function with pointers called!
Permission denied
secure function with pointers called!
Permission accepted
Return value: 0
BLXNS with misaligned SP is UNPREDICTABLE
Non-Secure World callback function called!
Exit Non-Secure World!

**Comment by luojia65** [comment]
Hello! I adjusted gitignore and xtask run script, now this project should run without error.
I'm closing this issue for problem solved, if not, please reply and I'll open this again.
