### ISSUE TITLE
Unable to find "Writing secure applications using Rust and TrustZone-M"

### ISSUE THREAD

**Issue by StefanHri** [luojia65/trustzone-m-rs#3]
Hi,

I am unable to find the document that you are referring to "Writing secure applications using Rust and TrustZone-M". Can you eventually provide a link or ideally a copy of the document within the repo?

Thanks!

**Comment by djovanoski** [comment]
im also unable to find it so it would be good to share it if you have any copy of that :) thanks

**Comment by luojia65** [comment]
@StefanHri , @djovanoski : please visit issue I6U0BY (https://gitee.com/cpdt/trustzone-m-rs/issues/I6U0BY) , thanks!
